# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

---
# Add branch labels to the PRs matching their branch names
branch/main:
 - base-branch: 'main'
branch/release-4.14:
 - base-branch: 'release-4.14'
branch/release-4.15:
 - base-branch: 'release-4.15'
branch/release-4.16:
 - base-branch: 'release-4.16'
branch/release-4.17:
 - base-branch: 'release-4.17'
branch/release-4.18:
 - base-branch: 'release-4.18'
