drClusterOperator:
  deploymentAutomationEnabled: true
  s3SecretDistributionEnabled: true
  channelName: alpha
  packageName: ramen-dr-cluster-operator
  namespaceName: ramen-system
  catalogSourceName: redhat-operators
  catalogSourceNamespaceName: openshift-marketplace
  clusterServiceVersionName: ramen-dr-cluster-operator.v0.0.1
